name: PADF Data Pipeline

on:
  schedule:
    # Ejecuta cada 2 horas (CRON en UTC)
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run-padf-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: true

      # Instala dependencias de R y system requirements (incl. para 'sf')
      # usando pak; 'extra-packages' asegura que se instalen y cacheen.
      - name: Set up R dependencies (pak)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::pacman
            any::dplyr
            any::tidyr
            any::httr
            any::jsonlite
            any::googledrive
            any::googlesheets4
            any::writexl
            any::haven
            any::stringr
            any::labelled
            any::lubridate
            any::gtsummary
            any::dotenv
            any::readxl
            any::tibble
            any::sf
            any::purrr

      - name: Run PADF master script
        env:
          GITHUB_ACTIONS: "true"
          SERVIDOR: ${{ secrets.SERVIDOR }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          FORMID: ${{ secrets.FORMID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          ID24: ${{ secrets.ID24 }}
          IDALERTAS: ${{ secrets.IDALERTAS }}
          IDKEYS: ${{ secrets.IDKEYS }}
        run: |
          Rscript PADF_master_script.R
