name: PADF Data Pipeline

on:
  schedule:
    # Ejecutar cada 2 horas
    - cron: "0 */2 * * *"
  workflow_dispatch: # Permite ejecución manual

jobs:
  run-padf-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Set up R dependencies
        run: |
          install.packages("pacman")
          library(pacman)
          pacman::p_load(
            dplyr, tidyr, httr, jsonlite,
            googledrive, googlesheets4, writexl,
            haven, stringr, labelled, lubridate,
            gtsummary, dotenv, readxl, tibble, sf, purrr
          )

      - name: Run PADF master script
        env:
          GITHUB_ACTIONS: "true"
          SERVIDOR: ${{ secrets.SERVIDOR }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          FORMID: ${{ secrets.FORMID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          ID24: ${{ secrets.ID24 }}
          IDALERTAS: ${{ secrets.IDALERTAS }}
          IDKEYS: ${{ secrets.IDKEYS }}
        run: |
          Rscript master_script_PADF.R
